## 빅데이터 실습

### 스타벅스매장 입지 분석

#### 데이터 수집

##### 웹 사이트 제공 엑셀파일 수정

In [22]:
# 필수 라이브러리
import pandas as pd
import numpy as np

In [13]:
dfSeoulManicipality = pd.read_excel('../day06/data/전국_시군구별_위경도.xlsx')
dfSeoulManicipality

      docity  do   city   longitude   latitude
0      강원강릉시  강원    강릉시  128.878497  37.749136
1      강원고성군  강원    고성군  128.470164  38.377961
2      강원동해시  강원    동해시  129.116633  37.521931
3      강원삼척시  강원    삼척시  129.167489  37.447086
4      강원속초시  강원    속초시  128.594167  38.204275
..       ...  ..    ...         ...        ...
290    충청충주시  충청    충주시  127.928144  36.988181
291    충청태안군  충청    태안군  126.299975  36.742667
292  충청한누리대로  충청  한누리대로  127.289926  36.485450
293    충청홍성군  충청    홍성군  126.662908  36.598361
294    충청대전시  충청    대전시  127.384862  36.350630

[295 rows x 5 columns]

In [14]:
# 서울 필터링
condition = dfSeoulManicipality['do'] == '서울'
dfSeoulGeo = dfSeoulManicipality[condition]

In [15]:
dfSeoulGeo

     docity  do  city   longitude   latitude
138   서울강남구  서울   강남구  127.049556  37.514575
139   서울강동구  서울   강동구  127.125864  37.527367
140   서울강북구  서울   강북구  127.027719  37.636956
141   서울강서구  서울   강서구  126.851675  37.548156
142   서울관악구  서울   관악구  126.953844  37.475386
143   서울광진구  서울   광진구  127.084533  37.535739
144   서울구로구  서울   구로구  126.889597  37.492650
145   서울금천구  서울   금천구  126.904197  37.449108
146   서울노원구  서울   노원구  127.058389  37.651461
147   서울도봉구  서울   도봉구  127.049522  37.665833
148  서울동대문구  서울  동대문구  127.042142  37.571625
149   서울동작구  서울   동작구  126.941575  37.509656
150   서울마포구  서울   마포구  126.910531  37.560706
151  서울서대문구  서울  서대문구  126.938897  37.576367
152   서울서초구  서울   서초구  127.034811  37.480786
153   서울성동구  서울   성동구  127.039000  37.560611
154   서울성북구  서울   성북구  127.020333  37.586383
155   서울송파구  서울   송파구  127.107931  37.511756
156   서울양천구  서울   양천구  126.868708  37.514231
157  서울영등포구  서울  영등포구  126.898342  37.523611
158   서울용산구  서울   용산구  126.967522  37.536094
159   서울은평구  서울   은평구  126.931242  37.599969
160   서울종로구  서울   종로구  126.981642  37.570378
161    서울중구  서울    중구  126.999642  37.561003
162   서울중랑구  서울   중랑구  127.094778  37.603806

In [26]:
# 필요로 만든 데이터는 항상 저장
dfSeoulGeo.to_excel('./data/수정_서울_시군구_위경도.xlsx', index=False)

In [32]:
# 서울시 구별 인구데이터 로드
dfSeoulPop = pd.read_excel('./data/서울시_구별_인구데이터.xlsx', header=2, usecols='B,O:Z')
columns = ['구', '세대소계', '남자', '여자', '한국인소계', '남자', '여자', '등록외국인소계', '남자', '여자', '세대당인구', '65세이상']
dfSeoulPop.columns = columns
dfSeoulPop

c:\DEV\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

ValueError: Length mismatch: Expected axis has 13 elements, new values have 12 elements

In [28]:
## 서울시 인구데이터 저장
dfSeoulPop.to_excel('./data/수정_서울_구별인구.xlsx', index=False)

In [29]:
dfSeoulWork = pd.read_excel('./data/서울시_구별_사업체현황.xlsx', header=4, usecols='B:G')
columns = ['구','소계','여성대표자','성별소계','남자','여자']
dfSeoulWork.columns = columns

c:\DEV\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [30]:
dfSeoulWork.tail()

      구      소계  여성대표자    성별소계      남자      여자
21  관악구   37915  13641  128417   68392   60025
22  서초구   71958  23066  487976  290084  197892
23  강남구  110007  35453  801419  447809  353610
24  송파구   74531  25400  400781  244588  156193
25  강동구   41660  15226  157465   83415   74050

In [31]:
## 서울시 구별 사업체현황 저장
dfSeoulWork.to_excel('./data/수정_서울_구별사업체.xlsx', index=False)